### PR TITLE
React & Redux group project - Space Travelers' Hub

### PR DESCRIPTION
**Pull request by deniodev**
- [ ] Config & basic setup.
- [ ]  Fetch data and update the Redux store.
- [ ]  Render UI:lists.
- [ ] Write actions and reducers for booking rockets and joining missions.
- [ ] Write actions and reducers for canceling rockets and leaving missions.
- [ ] Render UI: conditional components rendering.
- [ ] Render UI: My Profile section
- [ ] Add test for all components and functions.

### CODE REVIEW

**Review by divinecharlotte — CHANGES_REQUESTED** [review]
Hi @ Team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Clear commit messages👍 
- Clean code  👍 

 




 

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by deniodev** [comment]
Hi @divinecharlotte 

We didn't understand your request for changes, can you please clarify?

**Comment by deniodev** [comment]
Hi @divinecharlotte 

Please look at the refactored code to store specified rockets and missions data.

**Review by christianbiring1 — APPROVED** [review]
Hi @deniodev @WilhelmK109 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] Gret work on implementing the necessary changes as requested by the previous reviewer :+1: 
- [ ] Professional looking PR :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
